print("what is your name?")
name = input()
print("how old are you?")
age = int(input())
print("how tall are you?")
height = float(input())
print("How much do you weigh?")
weight = float(input())
print(name,"you are",age,"years old","and your height is",height)